routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', function () {
    return view('auth.login');
});


//Route::get('/home', 'NewsController@index')->name('home');
Route::get('/news/search/{search}','NewsController@search')->name('news.search');
Route::get('/news/deleted','NewsController@deleted')->name('news.deleted');
Route::get('/news/restore/{id}','NewsController@restore')->name('news.restore');
Route::get('/news/deleted/search/{search}','NewsController@search_del')->name('news.searchdel');
Route::resource('news', 'NewsController');

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class News extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at','created_at','updated_at'];
    protected $table="news";
    public $primaryKey="id";
    public $timestamps=true;

    public function user(){
        return $this->hasOne('App\User','id','id_user');
    }

    public function state(){
        return $this->hasOne('App\States','id','id_state');
    }

    public function scopeGetAllNews($query,int $trashed=null):Object{
        if($trashed){ 
             $query->onlyTrashed();
        }
            return $query->orderBy('created_at','desc')->paginate(5);
        

        /*
        $query->select("news.id","title","name as publisher","description as state","news.created_at","news.deleted_at")
        ->join('users','id_user','users.id')
        ->join('states','id_state','states.id');
        if($trashed){
            $query=$query->onlyTrashed();
        }
        $query=$query->orderBy('created_at','desc')->paginate(5);
        return $query;*/
    }

    public function scopestoreArticle($query,array $data,int $id=null):bool{
        if($id){
            $query->where('news.id',$id);
            return  $query->update($data);
        }
        else{
            return $query->insert($data);
        }      
    }
    
    public function scopegetArticle($query,int $id):Object{
        return $query->withTrashed()->where('news.id',$id)->first();

    //   return $query->select("news.id","title","content","name as publisher","description as state","id_state","news.created_at","news.deleted_at")
    //     ->join('users','id_user','users.id')
    //     ->join('states','id_state','states.id')
    //     ->orderBy('created_at','desc')
    //     ->withTrashed() #para que seja possivel visualizar os documentos
    //     ->where('news.id',$id)->first();
        
    }

    public function scopedestroyArticle($query,int $id):bool{
       return $query->where('news.id',$id)->delete();
        //($query->delete())?1:0;
    }


    public function scoperestoreArticle($query,int $id):bool{
        return $query->onlyTrashed()->where('news.id',$id)->restore();
    }

    public function scopesearchNews($query,array $data):Object{       
        $order="DESC";

        // $query->select("news.id","title","name as publisher","description as state","news.created_at","news.deleted_at")
        // ->join('users','id_user','users.id')
        // ->join('states','id_state','states.id');

        if($data['id_state']){
            $query=$query->where('id_state',$data['id_state']);
        }
        if($data['created_at']){
            $query=$query->whereDate('news.created_at', '=',$data['created_at']); # >= para incluir artigos a partir de X dia
            $order="ASC";
        }

        if($data['title']){
            $query=$query->where('title','like','%'.$data['title'].'%');
        }

        if($data['trashed']==1){
            $query=$query->onlyTrashed();
        }
        elseif($data['trashed']==2){
            $query=$query->withTrashed();
        }

        $query=$query->orderBy('created_at',$order);
        $query=$query->paginate(5);
        return $query;
        }
    }

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;
use App\States;
use App\User;
use App\News;
use Illuminate\Http\Request;

class NewsController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $news=News::GetAllNews();
        $states=States::All();
        $news->title="Artigos";
       return view('home',compact('news'),compact('states'));
    }

    
    public function deleted(){
        $news=News::GetAllNews(1);
        $states=States::All();
        $news->title="Artigos Apagados";
        return view('home',compact('news'),compact('states'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        $states=States::All();
        return view('news.create',compact('states'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
        $this->validate($request,[
            'title'=>'required|min:3',
            'content'=>'required|max:200',
            'state'=>'required',
        ]);

        $data=[
            "id"=>NULL,
            "title"=>$request->input('title'),
            "content"=>$request->input('content'),
            "id_user"=>auth()->user()->id,
            "id_state"=>$request->input('state'),
            "created_at" =>  \Carbon\Carbon::now(),
            "updated_at" => \Carbon\Carbon::now(),
        ];

        if(News::storeArticle($data))
            return redirect('/news')->with('flash-success','Noticia Criada com Sucesso');
        else
            return redirect('/news')->with('flash-error','Erro ao criar Noticia');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $article=News::getArticle($id);
        //$article=News::findOrFail($id);
        return view('news.show',compact('article'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $states=States::All();
        $article=News::getArticle($id);
        // $article=News::select("news.id","title","content","id_state")
        // ->where('news.id',$id)->first();
        return view('news.edit',compact('article'),compact('states'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'title'=>'required|min:3',
            'content'=>'required|max:200',
            'state'=>'required',
        ]);

        $data=[
            "title"=>$request->input('title'),
            "content"=>$request->input('content'),
            "id_state"=>$request->input('state')
        ];

        if(News::storeArticle($data,$id))
            return redirect('/news')->with('flash-success','Noticia Atualizada com Sucesso');
        else
            return redirect('/news')->with('flash-error','Erro ao Atualizar Noticia');  
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(News::destroyArticle($id))
            return redirect('/news')->with('flash-success','Noticia Apagada com Sucesso');
        else
            return redirect('/news')->with('flash-error','Erro ao tentar apagar Noticia');
    }

    public function restore($id){
        
        if(News::restoreArticle($id))
            return redirect('/news')->with('flash-success','Noticia Restaurada com Sucesso');
        else
            return redirect('/news')->with('flash-error','Erro ao tentar restaurar Noticia');
    }

       
    public function search(Request $request)
    {
        $this->validate($request,['trashed'=>'required']);

        $data=[
            'title'=>$request->input('qtitle'),
            'created_at'=>$request->input('qdate'),
            'id_state'=>$request->input('qstate'),
            'trashed'=>$request->input('trashed')
        ];

        $search=[
            'qtitle'=>$request->input('qtitle'),
            'qdate'=>$request->input('qdate'),
            'qstate'=>$request->input('qstate'),
            'trashed'=>$request->input('trashed')
        ];

        $news=News::searchNews($data);
        $states=States::All();
        $news->title="Resultados Da Pesquisa";
        return view('home',compact('news'),compact('states'),compact('data'));
    }  
}

resources/views/news/create.blade.php
@extends('layouts.app')
@section('content')
    
<div class="container">
    <h2>Criar Artigo</h2>
        <a href="{{route('news.index')}}"><button class="btn btn-primary"><i class="fas fa-chevron-left"></i>&nbsp; Voltar Atrás</button></a>
<form method="POST" id="formcreate" action="{{route('news.store')}}">
    @csrf
    <label for="title">Titulo:</label>
    <input type="text" class="form-control" name="title"><br>
    <label for="content">Conteudo: </label>
    <textarea class="form-control" name="content"></textarea>
    <label>Estado:</label>
    <select class="form-control" name="state">
    @if(count($states))
    @foreach($states as $state)
    <option value="{{$state->id}}">{{$state->description}}</option>
    @endforeach
    @else
     <option value="1">Publicado</option>
     <option value="2">Não Publicado</option>
    @endif
    </select><br>
    <button class="btn btn-primary" type="submit">Adicionar Noticia</button>
</form>
</div>
@endsection

resources/views/news/edit.blade.php
@extends('layouts.app')
@section('content')
    
<div class="container">
        <h2>Editar Artigo</h2>
        <a href="{{route('news.index')}}"><button class="btn btn-primary"><i class="fas fa-chevron-left"></i>&nbsp; Voltar Atrás</button></a>
    @if(isset($article))
  
<form method="POST" id="formcreate" action="{{route('news.update',$article->id)}}">
        {{method_field('PUT')}}
    @csrf
    <label for="title">Titulo:</label>
<input type="text" class="form-control" value="{{$article->title}}" name="title"><br>
    <label for="content">Conteudo: </label>
<textarea class="form-control" name="content">{{$article->content}}</textarea>
    <label>Estado:</label>
    <select class="form-control" name="state">
    @if(count($states))
    @foreach($states as $state)
    <option value="{{$state->id}}"@if($article->id_state ==$state->id) selected AQUI @endif>{{$state->description}}</option>
    @endforeach
    @else
     <option value="1">Publicado</option>
     <option value="2">Não Publicado</option>
    @endif  
    </select><br>
    <button class="btn btn-primary" type="submit">Guardar Alterações</button>
</form>
@else
<h1>Artigo Não encontrado!</h1>
@endif

</div>
@endsection

resources/views/news/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <a href="{{route('news.index')}}"><button class="btn btn-primary"><i class="fas fa-chevron-left"></i>&nbsp; Voltar Atrás</button></a>
<h2>{{$article->title}}</h2>
<small>Publicado a {{$article->created_at->format('Y-m-d H:i:s')}} por {{$article->user->name}}</small><br>
<h5 style="display:inline">Estado:</h5> <h6 style="display:inline; @if($article->deleted_at!=NULL) text-decoration: line-through"@else" @endif>{{$article->state->description}}@if($article->deleted_at!=NULL)<h5 class="alert-danger">ARTIGO APAGADO</h5>@endif</h6>
<h2 class="mt-2">Conteudo:</h2>
<div class="container  mt-3">
<div class="font-weight-light">{!!$article->content!!}</div>
</div>
@endsection